version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./public:/code:rw
      - ./nginx/sites.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: ./php
    restart: always
    volumes:
      - ./public:/code

