version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./public:/code:rw
      - /mnt/WEBSITE/dwc.local/Refview:/refview:rw
      - ./nginx/sites.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: ./php
    restart: always
    volumes:
      - ./public:/code
      - /mnt/WEBSITE/dwc.local/Refview:/refview
    links:
      - database

  database:
    build: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root


