version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    restart: always
    volumes_from:
      - workspace
    volumes:
      - ./nginx/sites.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: ./php
    restart: always
    volumes_from:
      - workspace
    links:
      - database

  database:
    build: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/maria:/var/lib/mysql:rw

  workspace:
    build:
      context: ./workspace
      args:
        - INSTALL_YARN=true
    volumes:
      - /mnt/WEBSITE/dwc.local/Refview:/refview:rw

